name: 6W2C Pipeline

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'renovate.json'
      - 'README.md'
    branches:
      - 'main'
      - 'develop'
      - 'feat/**'
  
jobs:
  build:
    uses: turbo5000c/am-reuseable-workflow/.github/workflows/AM_6W2C_main-workflow.yml@main
    secrets: inherit