name: Test

on:
  workflow_dispatch:

permissions:
  actions: read

jobs:
  call-shared-workflow:
    uses: turbo5000c/am-reuseable-workflow/.github/workflows/main.yml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
